const K='money-planner-app-v3';let db=JSON.parse(localStorage.getItem(K)||'{"tx":[],"goals":[],"accounts":[{"id":"cash","name":"เงินสด"}],"budgets":[],"settings":{"api":""},"queue":[]}');let page='home';
const save=()=>localStorage.setItem(K,JSON.stringify(db));const baht=n=>'฿'+Number(n||0).toLocaleString('th-TH',{maximumFractionDigits:2});const uid=()=>crypto.randomUUID?.()||Date.now()+'-'+Math.random();
function totals(){let inc=0,exp=0;db.tx.forEach(x=>x.type==='income'?inc+=+x.amount:exp+=+x.amount);return{inc,exp,bal:inc-exp}}
function txHtml(x){return `<div class="tx"><div class="avatar">${x.type==='income'?'↙':'↗'}</div><div><b>${esc(x.note||x.category)}</b><div class="mini">${x.date} · ${esc(x.category)}</div></div><div class="amount ${x.type}">${x.type==='income'?'+':'-'}${baht(x.amount)}</div><button class="danger" onclick="delTx('${x.id}')">×</button></div>`}
function esc(s=''){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function render(){const a=document.querySelector('#app');if(page==='home'){let t=totals();a.innerHTML=`<section class="hero"><small>ยอดเงินสุทธิ</small><div class="money">${baht(t.bal)}</div><div class="hero-grid"><div><small>รายรับทั้งหมด</small><b>+${baht(t.inc)}</b></div><div><small>รายจ่ายทั้งหมด</small><b>-${baht(t.exp)}</b></div></div></section><section class="card"><div class="row"><h3>รายการล่าสุด</h3><span class="pill">${db.tx.length} รายการ</span></div>${db.tx.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5).map(txHtml).join('')||'<div class="empty">ยังไม่มีรายการ กด + เพื่อเริ่มบันทึก</div>'}</section><section class="card"><div class="row"><h3>เป้าหมายของฉัน</h3><span class="pill">${db.goals.length}</span></div>${goalsHtml(2)}</section>`}else if(page==='tx'){a.innerHTML=`<div class="row"><h2>รายรับ–รายจ่าย</h2><span class="pill">ดูย้อนหลังทั้งหมด</span></div><section class="card">${db.tx.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(txHtml).join('')||'<div class="empty">ยังไม่มีข้อมูล</div>'}</section>`}else if(page==='goals'){a.innerHTML=`<div class="row"><h2>เป้าหมายการเงิน</h2><button class="primary" style="width:auto" onclick="goalForm()">+ เป้าหมาย</button></div>${goalsHtml(99)}` }else{settings(a)} }
function goalsHtml(n){return db.goals.slice(0,n).map(g=>{let p=Math.min(100,Math.round((+g.saved/+g.target)*100)||0);return `<section class="card"><div class="row"><div><b>${esc(g.name)}</b><div class="mini">${baht(g.saved)} / ${baht(g.target)}</div></div><b>${p}%</b></div><div class="progress"><i style="width:${p}%"></i></div><button class="pill" style="border:0" onclick="addSaving('${g.id}')">+ เพิ่มเงินออม</button></section>`}).join('')||'<section class="card empty">ยังไม่มีเป้าหมาย</section>'}
function settings(a){let st=db.settings.api?'<div class="status ok">● ตั้งค่า Google Sheets แล้ว</div>':'<div class="status wait">● ยังไม่ได้เชื่อม Google Sheets</div>';a.innerHTML=`<h2>ตั้งค่าและซิงก์</h2><section class="card"><h3>Google Sheets</h3>${st}<div class="field"><label>Apps Script Web App URL</label><input id="api" value="${esc(db.settings.api)}" placeholder="https://script.google.com/macros/s/.../exec"></div><button class="primary" onclick="saveApi()">บันทึกและทดสอบการเชื่อมต่อ</button><p class="setting-note">แอปจะเก็บข้อมูลในเครื่องก่อนเสมอ จึงบันทึกได้แม้ไม่มีอินเทอร์เน็ต เมื่อออนไลน์แล้วกด ↻ หรือเปิดแอปเพื่อซิงก์ขึ้น Google Sheets</p></section><section class="card"><h3>สำรองข้อมูล</h3><button class="primary" onclick="backup()">ส่งออก Backup (.json)</button><div class="field"><label>นำ Backup กลับเข้าแอป</label><input type="file" id="restore" accept="application/json" onchange="restoreFile(this)"></div></section>`}
function openTx(){show(`<div class="field"><label>ประเภท</label><select name="type"><option value="expense">รายจ่าย</option><option value="income">รายรับ</option></select></div><div class="field"><label>จำนวนเงิน</label><input name="amount" type="number" step="0.01" required></div><div class="field"><label>หมวดหมู่</label><input name="category" placeholder="อาหาร / เงินเดือน / เดินทาง" required></div><div class="field"><label>รายละเอียด</label><input name="note" placeholder="รายละเอียดเพิ่มเติม"></div><div class="field"><label>วันที่</label><input name="date" type="date" value="${new Date().toISOString().slice(0,10)}" required></div><button class="primary">บันทึกรายการ</button>`,fd=>{let x=Object.fromEntries(fd);x.id=uid();x.amount=+x.amount;x.updatedAt=new Date().toISOString();db.tx.unshift(x);enqueue('upsert','Transactions',x);save();render();sync()})}
function goalForm(){show(`<div class="field"><label>ชื่อเป้าหมาย</label><input name="name" required placeholder="เช่น ซื้อรถ"></div><div class="field"><label>ยอดเป้าหมาย</label><input name="target" type="number" required></div><div class="field"><label>มีแล้ว</label><input name="saved" type="number" value="0"></div><button class="primary">สร้างเป้าหมาย</button>`,fd=>{let g=Object.fromEntries(fd);g.id=uid();g.target=+g.target;g.saved=+g.saved;g.updatedAt=new Date().toISOString();db.goals.push(g);enqueue('upsert','Goals',g);save();close();render();sync()})}
function addSaving(id){let v=prompt('เพิ่มเงินออมจำนวนเท่าไร?');if(!v||isNaN(v))return;let g=db.goals.find(x=>x.id===id);g.saved+=+v;g.updatedAt=new Date().toISOString();enqueue('upsert','Goals',g);save();render();sync()}
function delTx(id){if(!confirm('ลบรายการนี้?'))return;db.tx=db.tx.filter(x=>x.id!==id);enqueue('delete','Transactions',{id});save();render();sync()}
function enqueue(action,sheet,data){db.queue.push({id:uid(),action,sheet,data,at:new Date().toISOString()});save()}
function show(html,cb){document.querySelector('#modal').classList.remove('hidden');document.querySelector('#form').innerHTML=html;document.querySelector('#form').onsubmit=e=>{e.preventDefault();cb(new FormData(e.target));close()}}
function close(){document.querySelector('#modal').classList.add('hidden')}
function saveApi(){db.settings.api=document.querySelector('#api').value.trim();save();sync(true)}
async function sync(test=false){if(!db.settings.api||!navigator.onLine)return;try{let payload={action:'sync',device:'MoneyPlannerApp',queue:db.queue,client:{Transactions:db.tx,Goals:db.goals,Accounts:db.accounts,Budgets:db.budgets}};let r=await fetch(db.settings.api,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});let j=await r.json();if(!j.ok)throw Error(j.error||'sync failed');if(j.data){db.tx=j.data.Transactions||db.tx;db.goals=j.data.Goals||db.goals;db.accounts=j.data.Accounts||db.accounts;db.budgets=j.data.Budgets||db.budgets}db.queue=[];save();render();if(test)alert('เชื่อมต่อ Google Sheets สำเร็จ ✓')}catch(e){if(test)alert('ยังเชื่อมต่อไม่ได้: '+e.message)}}
function backup(){let b=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='money-planner-app-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click()}
function restoreFile(i){let f=i.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{db=JSON.parse(r.result);save();render();alert('นำข้อมูลกลับสำเร็จ')}catch{alert('ไฟล์ Backup ไม่ถูกต้อง')}};r.readAsText(f)}
document.querySelectorAll('nav [data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});document.querySelector('#addBtn').onclick=openTx;document.querySelector('#closeBtn').onclick=e=>{e.preventDefault();close()};document.querySelector('#syncBtn').onclick=()=>sync(true);window.addEventListener('online',()=>sync());if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');render();sync();
